(function(){
let currentBookType=null,currentEpubBook=null,currentRendition=null,currentPdfDoc=null,currentPdfTotalPages=0,currentPdfPageNum=1,currentTxtRaw=null,currentTxtChunks=[],smartChapterMode=!0,currentChapterIndex=0,currentFileName="",currentFontSize=100,currentTheme="light",currentBookUrlOrId="";
let chunkTextCache={};
const readerContainer=document.getElementById('readerContainer'),readerArea=document.getElementById('readerArea'),fileInput=document.getElementById('fileInput'),searchInput=document.getElementById('searchInput'),clearSearchBtn=document.getElementById('clearSearchBtn'),searchDropdown=document.getElementById('searchDropdown'),localMatchList=document.getElementById('localMatchList'),globalMatchList=document.getElementById('globalMatchList'),toolbarOverlay=document.getElementById('toolbarOverlay'),sidebar=document.getElementById('sidebar'),sidebarMask=document.getElementById('sidebarMask'),tocListEl=document.getElementById('tocList'),bookTitleEl=document.getElementById('bookTitle'),themeToggleBtn=document.getElementById('themeToggleBtn');
let currentSearchTerm="",currentSearchMatches=[],searchDebounceTimer;
let db=null;
const DB_NAME="ZZXMobileDB",STORE_NAME="books";
function initDB(){return new Promise((resolve,reject)=>{const req=indexedDB.open(DB_NAME,1);req.onerror=()=>reject(req.error);req.onsuccess=()=>{db=req.result;resolve(db)};req.onupgradeneeded=e=>{const dbr=e.target.result;if(!dbr.objectStoreNames.contains(STORE_NAME))dbr.createObjectStore(STORE_NAME,{keyPath:"id"})}})}
async function saveBook(id,blob,name,type){if(!db)await initDB();const tx=db.transaction([STORE_NAME],"readwrite");tx.objectStore(STORE_NAME).put({id,blob,fileName:name,fileType:type,timestamp:Date.now()})}
async function loadBook(id){if(!db)await initDB();return new Promise(resolve=>{const tx=db.transaction([STORE_NAME],"readonly"),req=tx.objectStore(STORE_NAME).get(id);req.onsuccess=()=>resolve(req.result)})}
function saveConfig(){localStorage.setItem("zzx_mob_config",JSON.stringify({fontSize:currentFontSize,theme:currentTheme,smartMode:smartChapterMode,lastBookId:currentBookUrlOrId,lastType:currentBookType,lastFileName:currentFileName,pdfPage:currentPdfPageNum,chapterIndex:currentChapterIndex}))}
function loadConfig(){const raw=localStorage.getItem("zzx_mob_config");if(raw){try{const c=JSON.parse(raw);currentFontSize=c.fontSize||100;currentTheme=c.theme||"light";smartChapterMode=c.smartMode!==!1;setTheme(currentTheme);adjustFontSize(0);return c}catch(e){}}return{}}
function getChapterContent(idx){if(idx<0||idx>=currentTxtChunks.length)return null;if(!chunkTextCache[idx])chunkTextCache[idx]=currentTxtChunks[idx].content;return chunkTextCache[idx]}
function buildChapterHTML(idx){const ch=currentTxtChunks[idx];return `<div class="chapter-title">${escapeHtml(ch.title||'')}</div><div class="txt-viewer" style="font-size:${(currentFontSize/100)*1.1}rem; color:${currentTheme==='dark'?'#e2e8f0':'#1e293b'}">${escapeHtml(getChapterContent(idx))}</div>`}
function renderChapter(idx){if(!currentTxtChunks.length)return;currentChapterIndex=Math.min(Math.max(0,idx),currentTxtChunks.length-1);readerArea.innerHTML=buildChapterHTML(currentChapterIndex);readerArea.scrollTop=0;bookTitleEl.innerText=currentTxtChunks[currentChapterIndex].title||currentFileName;updateTOCActive();preloadNearbyChapters(currentChapterIndex);saveProgress()}
function updateTOCActive(){const items=tocListEl.querySelectorAll('.toc-item');items.forEach((item,i)=>{item.classList.toggle('active',i===currentChapterIndex)})}
function preloadNearbyChapters(centerIdx){const start=Math.max(0,centerIdx-10),end=Math.min(currentTxtChunks.length-1,centerIdx+10);for(let i=start;i<=end;i++){if(!chunkTextCache[i])chunkTextCache[i]=currentTxtChunks[i].content}}
function onReaderScroll(){if(currentBookType!=='txt'||!smartChapterMode||!currentTxtChunks.length)return;const st=readerArea.scrollTop,sh=readerArea.scrollHeight,ch=readerArea.clientHeight,threshold=50;if(st<=threshold&&currentChapterIndex>0)loadAdjacentChapter(currentChapterIndex-1,'top');else if(st+ch>=sh-threshold&&currentChapterIndex<currentTxtChunks.length-1)loadAdjacentChapter(currentChapterIndex+1,'bottom')}
function loadAdjacentChapter(newIdx,direction){if(newIdx<0||newIdx>=currentTxtChunks.length)return;const oldSH=readerArea.scrollHeight,html=buildChapterHTML(newIdx);if(direction==='top'){const temp=document.createElement('div');temp.innerHTML=html;while(temp.firstChild)readerArea.insertBefore(temp.firstChild,readerArea.firstChild);readerArea.scrollTop=readerArea.scrollHeight-oldSH}else if(direction==='bottom'){const temp=document.createElement('div');temp.innerHTML=html;while(temp.firstChild)readerArea.appendChild(temp.firstChild)}currentChapterIndex=newIdx;bookTitleEl.innerText=currentTxtChunks[currentChapterIndex].title||currentFileName;updateTOCActive();preloadNearbyChapters(currentChapterIndex);saveProgress()}
async function loadEpub(buffer,filename){clearReader();currentBookType='epub';currentFileName=filename;const blob=new Blob([buffer],{type:'application/epub+zip'});currentEpubBook=ePub(URL.createObjectURL(blob));currentRendition=currentEpubBook.renderTo("readerArea",{width:"100%",height:"100%",spread:"none",flow:"paginated"});await currentRendition.display();currentRendition.themes.register('light',{body:{background:'#fefefe',color:'#1e293b'}});currentRendition.themes.register('dark',{body:{background:'#11131f',color:'#e2e8f0'}});setTheme(currentTheme);currentRendition.themes.fontSize(currentFontSize+"%");const nav=await currentEpubBook.loaded.navigation;buildEpubToc(nav.toc);currentRendition.on('relocated',()=>{});bookTitleEl.innerText=filename;await loadProgress()}
function buildEpubToc(toc){tocListEl.innerHTML='';const renderItems=(items,parent)=>{items.forEach(item=>{const li=document.createElement('li');li.className='toc-item';li.innerText=item.label||'章节';if(item.href)li.addEventListener('click',()=>{currentRendition.display(item.href);closeSidebar()});parent.appendChild(li);if(item.subitems)renderItems(item.subitems,parent)})};renderItems(toc,tocListEl)}
async function loadPdf(buffer,filename){clearReader();currentBookType='pdf';currentFileName=filename;currentPdfDoc=await pdfjsLib.getDocument({data:new Uint8Array(buffer)}).promise;currentPdfTotalPages=currentPdfDoc.numPages;currentPdfPageNum=1;await renderAllPdfPages();buildPdfToc();bookTitleEl.innerText=filename;await loadProgress()}
async function renderAllPdfPages(){readerArea.innerHTML='';for(let i=1;i<=currentPdfTotalPages;i++){const page=await currentPdfDoc.getPage(i),vp=page.getViewport({scale:1.5}),canvas=document.createElement('canvas');canvas.height=vp.height;canvas.width=vp.width;canvas.className='pdf-page-canvas';await page.render({canvasContext:canvas.getContext('2d'),viewport:vp}).promise;readerArea.appendChild(canvas)}}
function buildPdfToc(){tocListEl.innerHTML='';for(let i=1;i<=currentPdfTotalPages;i++){const li=document.createElement('li');li.className='toc-item';li.innerText=`第${i}页`;li.addEventListener('click',()=>{const target=document.querySelector(`.pdf-page-canvas:nth-child(${i})`);if(target)target.scrollIntoView({behavior:'smooth'});closeSidebar()});tocListEl.appendChild(li)}}
async function loadTxt(buffer,filename){clearReader();currentBookType='txt';currentFileName=filename;const enc=await detectEncoding(buffer);currentTxtRaw=new TextDecoder(enc).decode(buffer);currentTxtChunks=splitIntelligentChapters(currentTxtRaw);smartChapterMode=!0;preloadNearbyChapters(0);renderChapter(0);buildTocFromChunks();bookTitleEl.innerText=currentTxtChunks[0]?.title||filename;await loadProgress()}
function buildTocFromChunks(){tocListEl.innerHTML='';currentTxtChunks.forEach((ch,i)=>{const li=document.createElement('li');li.className='toc-item';li.innerText=ch.title.length>20?ch.title.slice(0,18)+'…':ch.title;li.addEventListener('click',()=>{renderChapter(i);closeSidebar()});tocListEl.appendChild(li)})}
async function loadTxtWithSmartChapter(){if(smartChapterMode&&currentTxtChunks.length){renderChapter(currentChapterIndex);buildTocFromChunks()}else{readerArea.innerHTML=`<div class="txt-viewer" style="font-size:${(currentFontSize/100)*1.1}rem; color:${currentTheme==='dark'?'#e2e8f0':'#1e293b'}">${escapeHtml(currentTxtRaw)}</div>`;tocListEl.innerHTML='<li class="toc-item">纯文本全文</li>';bookTitleEl.innerText=currentFileName}}
function clearReader(){if(currentRendition)try{currentRendition.destroy()}catch(e){}if(currentEpubBook)try{currentEpubBook.destroy()}catch(e){}currentPdfDoc=null;currentTxtRaw=null;currentTxtChunks=[];chunkTextCache={};readerArea.innerHTML='<div class="empty-state"><i class="fas fa-cloud-upload-alt" style="font-size:48px;opacity:0.4"></i><p>点击屏幕中央<br>上传图书开始阅读</p></div>';currentBookType=null;tocListEl.innerHTML='<li class="empty-toc">暂无目录</li>';bookTitleEl.innerText='未打开书籍'}
function setTheme(theme){currentTheme=theme;document.body.classList.toggle('dark',theme==='dark');if(currentBookType==='epub'&&currentRendition)currentRendition.themes.select(theme);saveConfig()}
function adjustFontSize(delta){currentFontSize=Math.min(180,Math.max(70,currentFontSize+delta));if(currentBookType==='epub'&&currentRendition)currentRendition.themes.fontSize(currentFontSize+"%");if(currentBookType==='txt'){if(smartChapterMode&&currentTxtChunks.length)renderChapter(currentChapterIndex);else if(!smartChapterMode&&currentTxtRaw)readerArea.querySelector('.txt-viewer').style.fontSize=(currentFontSize/100)*1.1+"rem"}saveConfig()}
async function detectEncoding(buffer){const encodings=['utf-8','gbk','gb2312','big5','shift-jis','euc-kr'],sample=buffer.slice(0,4096);function scoreText(text){let v=0;for(let i=0;i<text.length&&i<1000;i++){const c=text.charCodeAt(i);if((c>=0x4E00&&c<=0x9FFF)||(c>=0x3040&&c<=0x30FF)||(c>=0xAC00&&c<=0xD7AF)||(c>=0x20&&c<=0x7E)||c===0x0A||c===0x0D||c===0x09)v++}return v/(text.length||1)}let best='utf-8',bestScore=0;for(const e of encodings){try{const t=new TextDecoder(e,{fatal:!1}).decode(sample),s=scoreText(t);if(s>bestScore){bestScore=s;best=e}if(bestScore>.95)break}catch(e){}}return best}
function splitIntelligentChapters(text){const unitCounter={},pat=/^第([\d零一二三四五六七八九十百千万]+)([章节卷回部篇集辑课程])/gm;let m;while((m=pat.exec(text))!==null)unitCounter[m[2]]=(unitCounter[m[2]]||0)+1;let bestUnit=null,max=0;for(const u in unitCounter)if(unitCounter[u]>max){max=unitCounter[u];bestUnit=u}const splitPat=bestUnit?new RegExp(`^(第[\\d零一二三四五六七八九十百千万]+${bestUnit})`,'gm'):/^(第[\d零一二三四五六七八九十百千万]+[章节卷回部篇集辑课程]?)/gm;const lines=text.split(/\r?\n/),chapters=[];let curTitle="序言",curContent=[];for(const line of lines){const t=line.trim();splitPat.lastIndex=0;if(splitPat.test(t)&&t.length<50){if(curContent.length)chapters.push({title:curTitle,content:curContent.join('\n')});curTitle=t;curContent=[]}else curContent.push(line)}if(curContent.length)chapters.push({title:curTitle,content:curContent.join('\n')});if(!chapters.length)chapters=[{title:"全文",content:text}];return chapters}
function escapeHtml(s){return s.replace(/[&<>]/g,c=>c==='&'?'&amp;':c==='<'?'&lt;':'&gt;')}
function clearSearch(){currentSearchTerm="";searchInput.value="";searchDropdown.style.display="none";removeHighlights();localMatchList.innerHTML="";globalMatchList.innerHTML="";clearSearchBtn.classList.remove('show')}
function performSearch(query){currentSearchTerm=query;if(!query.trim()){searchDropdown.style.display="none";removeHighlights();clearSearchBtn.classList.remove('show');return}clearSearchBtn.classList.add('show');const lowerQuery=query.toLowerCase(),localText=getCurrentVisibleText(),localMatches=[];let idx=localText.toLowerCase().indexOf(lowerQuery);while(idx!==-1){const start=Math.max(0,idx-20),end=Math.min(localText.length,idx+query.length+20);localMatches.push({start:idx,end:idx+query.length,text:localText.slice(start,end).replace(/\n/g,' ')});idx=localText.toLowerCase().indexOf(lowerQuery,idx+1)}currentSearchMatches=localMatches;localMatchList.innerHTML=localMatches.length?localMatches.map(m=>`<li>...${escapeHtml(m.text)}...</li>`).join(''):'<li>无匹配</li>';const globalRes=[];if(currentBookType==='txt'&&smartChapterMode&&currentTxtChunks.length){currentTxtChunks.forEach((ch,i)=>{const cnt=(getChapterContent(i)||'').toLowerCase().split(lowerQuery).length-1;if(cnt>0)globalRes.push({chapterIndex:i,title:ch.title,count:cnt})})}globalMatchList.innerHTML=globalRes.length?globalRes.map(r=>`<li data-chapter="${r.chapterIndex}">${escapeHtml(r.title)} (${r.count})</li>`).join(''):'<li>全文无匹配</li>';searchDropdown.style.display="block";highlightLocalMatches()}
function getCurrentVisibleText(){if(currentBookType==='txt'){if(smartChapterMode&&currentTxtChunks.length)return getChapterContent(currentChapterIndex)||'';return currentTxtRaw||''}return readerArea.innerText||''}
function highlightLocalMatches(){removeHighlights();if(!currentSearchTerm)return;const container=document.querySelector('.txt-viewer');if(container){const regex=new RegExp(`(${escapeRegex(currentSearchTerm)})`,'gi');container.innerHTML=container.innerHTML.replace(regex,'<mark>$1</mark>')}}
function removeHighlights(){const container=document.querySelector('.txt-viewer');if(container)container.innerHTML=container.innerHTML.replace(/<\/?mark[^>]*>/gi,'')}
function escapeRegex(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function openToolbar(){toolbarOverlay.style.display='block'}function closeToolbar(){toolbarOverlay.style.display='none'}function toggleToolbar(){toolbarOverlay.style.display==='block'?closeToolbar():openToolbar()}function openSidebar(){sidebar.classList.add('open');sidebarMask.style.display='block'}function closeSidebar(){sidebar.classList.remove('open');sidebarMask.style.display='none'}
readerContainer.addEventListener('click',e=>{if(toolbarOverlay.style.display==='block'&&!e.target.closest('.toolbar-overlay'))closeToolbar()});
sidebarMask.addEventListener('click',closeSidebar);
document.getElementById('closeSidebarBtn').addEventListener('click',closeSidebar);
document.getElementById('tapCenter').addEventListener('click',e=>{e.stopPropagation();toggleToolbar()});
document.getElementById('tapLeft').addEventListener('click',e=>{e.stopPropagation();if(currentBookType==='epub')currentRendition?.prev();else if(currentBookType==='pdf')readerArea.scrollBy({top:-readerContainer.clientHeight,behavior:'smooth'});});
document.getElementById('tapRight').addEventListener('click',e=>{e.stopPropagation();if(currentBookType==='epub')currentRendition?.next();else if(currentBookType==='pdf')readerArea.scrollBy({top:readerContainer.clientHeight,behavior:'smooth'});});
document.getElementById('fileUploadBtn').addEventListener('click',()=>fileInput.click());
fileInput.addEventListener('change',async e=>{if(e.target.files.length){await processFile(e.target.files[0]);fileInput.value=''}});
document.getElementById('urlLoadBtn').addEventListener('click',()=>{const url=prompt('输入图书URL:');if(url)loadFromUrl(url).catch(err=>alert('加载失败: '+err.message))});
document.getElementById('fontMinusBtn').addEventListener('click',()=>adjustFontSize(-10));
document.getElementById('fontPlusBtn').addEventListener('click',()=>adjustFontSize(10));
themeToggleBtn.addEventListener('click',()=>setTheme(currentTheme==='light'?'dark':'light'));
document.getElementById('smartChapterBtn').addEventListener('click',()=>{if(currentBookType!=='txt')return;smartChapterMode=!smartChapterMode;localStorage.setItem(`txt_smart_mode_${currentFileName}`,smartChapterMode);loadTxtWithSmartChapter();closeToolbar()});
document.getElementById('tocBtn').addEventListener('click',()=>{openSidebar();closeToolbar()});
searchInput.addEventListener('input',()=>{clearTimeout(searchDebounceTimer);searchDebounceTimer=setTimeout(()=>performSearch(searchInput.value),300)});
clearSearchBtn.addEventListener('click',clearSearch);
document.addEventListener('click',e=>{if(!e.target.closest('.search-row'))searchDropdown.style.display='none'});
localMatchList.addEventListener('click',e=>{const li=e.target.closest('li');if(!li||!currentSearchMatches.length)return;const index=Array.from(localMatchList.children).indexOf(li),match=currentSearchMatches[index];if(!match)return;const container=document.querySelector('.txt-viewer');if(container){const walker=document.createTreeWalker(container,NodeFilter.SHOW_TEXT);let node,offset=0;while((node=walker.nextNode())){const len=node.textContent.length;if(offset+len>match.start){const range=document.createRange();range.setStart(node,match.start-offset);range.setEnd(node,match.end-offset);range.startContainer.parentElement.scrollIntoView({behavior:'smooth',block:'center'});break}offset+=len}}});
globalMatchList.addEventListener('click',e=>{const li=e.target.closest('li');if(!li)return;const chapterIdx=parseInt(li.dataset.chapter,10);if(!isNaN(chapterIdx)&&currentTxtChunks.length){renderChapter(chapterIdx);closeToolbar();setTimeout(()=>performSearch(currentSearchTerm),300)}});
readerArea.addEventListener('scroll',()=>{if(currentBookType==='txt'&&smartChapterMode)onReaderScroll()});
async function saveProgress(){if(!currentFileName)return;const key=`m_progress_${currentFileName}`;let data={type:currentBookType};if(currentBookType==='epub'&&currentRendition){try{const loc=currentRendition.currentLocation();if(loc?.start?.cfi)data.cfi=loc.start.cfi}catch(e){}}else if(currentBookType==='pdf')data.page=currentPdfPageNum;else if(currentBookType==='txt')data.chapterIndex=currentChapterIndex;localStorage.setItem(key,JSON.stringify(data))}
async function loadProgress(){if(!currentFileName)return;const raw=localStorage.getItem(`m_progress_${currentFileName}`);if(!raw)return;try{const data=JSON.parse(raw);if(data.type==='epub'&&currentBookType==='epub'&&data.cfi){currentRendition.display(data.cfi)}else if(data.type==='pdf'&&currentBookType==='pdf'){const target=document.querySelector(`.pdf-page-canvas:nth-child(${data.page||1})`);if(target)target.scrollIntoView()}else if(data.type==='txt'&&currentBookType==='txt'){renderChapter(data.chapterIndex||0)}}catch(e){}}
async function processFile(file){if(!file)return;const name=file.name,ext=name.split('.').pop().toLowerCase();const buffer=await file.arrayBuffer();currentBookUrlOrId=`file_${name}_${Date.now()}`;await saveBook(currentBookUrlOrId,new Blob([buffer]),name,ext);currentFileName=name;clearSearch();if(ext==='epub')await loadEpub(buffer,name);else if(ext==='pdf')await loadPdf(buffer,name);else if(ext==='txt')await loadTxt(buffer,name);closeToolbar();saveConfig()}
async function loadFromUrl(url){const resp=await fetch(url);if(!resp.ok)throw new Error(`HTTP ${resp.status}`);const blob=await resp.blob();const filename=url.split('/').pop()||"book";await processFile(new File([blob],filename))}
function updateDateTimeBattery(){const el=document.getElementById('batteryTime');if(!el)return;const now=new Date();const timeStr=`${String(now.getHours()).padStart(2,'0')}:${String(now.getMinutes()).padStart(2,'0')}`;if(navigator.getBattery){navigator.getBattery().then(battery=>{const level=Math.round(battery.level*100);el.textContent=`${level}% · ${timeStr}`;battery.addEventListener('levelchange',()=>{el.textContent=`${Math.round(battery.level*100)}% · ${timeStr}`})}).catch(()=>{el.textContent=timeStr})}else el.textContent=timeStr}
updateDateTimeBattery();
setInterval(updateDateTimeBattery,30000);
const cfg=loadConfig();
setTheme(currentTheme);
adjustFontSize(0);
(async()=>{if(cfg.lastBookId){const record=await loadBook(cfg.lastBookId);if(record?.blob){const file=new File([record.blob],record.fileName,{type:`application/${record.fileType}`});await processFile(file)}}})();
})();
